# Introduction

## Go Google Yourself!

Let's ask something: What if someone wants to know what the internet says about him/her? This question has been asked several times, and there's a bunch of actors involved on this topic. But let's rethink the question to make it a little bit more realistic; What if one want to knows what Google know about him/her?  

As we might think this is a bit clear to understand, it is less ambiguous and answerable. One of the most important motivations of this project is getting closer to that answer. Everyone spend so much time a day on the web, on different purposes, and there are some companies that they actually have our navigation data, as Google, even though is free and downloadable, one should have certain knowledge to get insights about our data.      

_The goal of the project is getting the Google data insights accessible to everyone_.  

On the other hand, is a little bit more optimistic, to think that everything in the world is going to be solved with Recommender Systems based on one data, that is a lie, but the truth is the world is shaping on _data driven things_ , and as the number of items in markets increases, the quantity of available choices also increases. Consequently, users might face lots of irrelevant data when looking for an item. This problem could be felt when users face numerous items which can confuse them to choose what they are looking for, that is why Recommender System have achieved immerse in consumer experience. Another motivation for the study is reaching the different ways a person might have knowledge based on the data we permitted to Google to use.  

## Google Takeout

First of all, we have to understand the data we are using, Google Takeout is the backup service provided to you through your Google Apps Account. One has to log into those public services in order to have access to this feature. The reader has to make sure is logged into your Google Apps account and then navigate to [Google Takeout](https://takeout.google.com/settings/takeout) interface.  

Google Takeout was created by the Google Data Liberation Front on June 28, 2011 to allow users to export their data from most of Google's services. Since its creation, Google has added several more services to Takeout due to popular demand for the user.[1]  

The user can select to export all the available services or choose services from the above list. Takeout (Takeaway in other languages) will then process the request and put all the files into a zip file. Takeout then optionally sends an email notification that the export is completed, at which point the user can download the archive from the downloads section of the website. The zip file contains a separate folder for each service that was selected for export.  

One might say, the developers can access other's data, but one have to be careful because of the personal data rights, in general whether information relates to an identified or identifiable individual, this should be always clear to understand when one is using other's data. [2] The privacy may be an archaic term when used in reference to depositing information online. Unlike writing a note of secrecy and keeping it safely guarded inside a vault, keeping information hidden and secure online is radically different. We live in an age where we all feel like rulers to our information, kings and queens of online accounts, yet we are not, maybe because of the lack of information on this matter.  

## Recommender Systems

Recommender Systems are software tools and techniques providing suggestions for items to be of use to a user. The suggestions relate to various decision-making processes, such as what items to consume.[3]  

It is clear to scope the new notion, see data as a currency, and Recommendation Systems are tools capable of predicting the preferences of users over sets of items (given the historical user-preference data). These systems can be found almost everywhere in the digital space (e.g. Amazon, Google, Netflix), shaping the choices we make, the products we buy, the books we read, or movies we watch. Al those are typically produced a list of recommendations in one of two ways: Through collaborative and content-based filtering or the personality-based approach. Collaborative filtering approaches building a model from a user's past behavior (items previously purchased or selected and/or numerical ratings given to those items) as well as similar decisions made by other users. This model is then used to predict items (or ratings for items) that the user may have an interest in.  

Moreover, Recommender Systems always provides the users with the best available choice. In this case, a recommendation model can be applied in order to help users to find what they are looking for faster and easier. In general, the model analyzes the existing data to generate the recommendation list. For this study, It is been going to merge the data from people on the most common Google applications. As a result, users could find what they are looking for, on their favorites places around in a shorter time and desirable a higher precision. It is important to say that optimize the algorithms is the very next step.[4]  